import { ICategory } from "@/entities/category/model";
import { IDish } from "@/entities/dish/model";

export const MENU_CATEGORIES: ICategory[] = [
    { id: 0, name: "Ассорти", slug: "assorti" },
    { id: 1, name: "Завтраки", slug: "zavtraki" },
    { id: 5, name: "Супы", slug: "supy" },
    { id: 6, name: "Салаты", slug: "salaty" },

    { id: 10, name: "Шашлык", slug: "shashlyk" },
    { id: 11, name: "Овощи гриль", slug: "ovoshchi-gril" },
    { id: 12, name: "Рыба гриль", slug: "ryba-gril" },
    { id: 13, name: "Люля-кебаб", slug: "lyulya-kebab" },

    { id: 14, name: "Бурум", slug: "burum" },
    { id: 15, name: "Шаурма", slug: "shaurma" },

    { id: 16, name: "Wok", slug: "wok" },
    { id: 17, name: "Роллы", slug: "rolly" },

    { id: 7, name: "Закуски", slug: "zakuski" },
    { id: 9, name: "Соусы", slug: "sousy" },

    { id: 18, name: "Горячие напитки", slug: "goryachie-napitki" },
    { id: 19, name: "Холодные напитки", slug: "holodnye-napitki" },
];

export const dishes: IDish[] = [
    // Ассорти
    {
        id: 0,
        name: "Ассорти №1",
        description:
            "4 вида люля, 3 порции шейки, 1 порция куриного филе, 1 порция молодого картофеля на углях, 1 порция грибов, 1 порция овощного микса, лук, зелень, шашлычный соус, чесночный соус, лаваш армянский",
        slug: "assorti-1",
        weightValue: 2.5,
        weightUnit: "кг",
        price: 6710,
        categoryId: 0,
    },
    {
        id: 1,
        name: "Ассорти №2",
        description:
            "4 вида люля, 1 порция шейки, 1 порция куриного филе, 1 порция молодого картофеля на углях, 1 порция грибов, 1 порция овощного микса, лук, зелень, шашлычный соус, чесночный соус, лаваш армянский",
        slug: "assorti-2",
        weightValue: 2,
        weightUnit: "кг",
        price: 5060,
        categoryId: 0,
    },
    {
        id: 2,
        name: "Ассорти №3",
        description:
            "1 порция розовой телятины, 1 порция бараньей мякоти, 1 порция бараньей корейки, 1 порция филе курицы, 1 порция люля баранины, 1 порция овощного микса, лук, зелень, шашлычный соус, лаваш армянский",
        slug: "assorti-3",
        weightValue: 1.5,
        weightUnit: "кг",
        price: 5500,
        categoryId: 0,
    },
    {
        id: 3,
        name: "Ассорти овощей на углях",
        description: "Перец болгарский, помидор, баклажан, перец армянский",
        slug: "assorti-ovoshchey-na-uglyah",
        weightValue: 500,
        weightUnit: "г",
        price: 1045,
        categoryId: 0,
    },

    // Шаурма
    {
        id: 4,
        name: "Шаурма с курицей",
        description:
            "Куриная мякоть, соус шашлычный, соус чесночный, помидор, морковь, маринованные огурцы, пекинская капуста, лук, зелень",
        slug: "shaurma-s-kuricey",
        weightValue: 350,
        weightUnit: "г",
        price: 363,
        categoryId: 15,
    },
    {
        id: 5,
        name: "Шаурма со свининой",
        description:
            "Свиная мякоть, соус шашлычный, соус чесночный, помидор, морковь, маринованные огурцы, пекинская капуста, лук, зелень",
        slug: "shaurma-so-svininoy",
        weightValue: 350,
        weightUnit: "г",
        price: 440,
        categoryId: 15,
    },
    {
        id: 6,
        name: "Шаурма с бараниной",
        description:
            "Мякоть баранины, соус шашлычный, соус чесночный, помидор, морковь, маринованные огурцы, пекинская капуста, лук, зелень",
        slug: "shaurma-s-baraninoy",
        weightValue: 350,
        weightUnit: "г",
        price: 484,
        categoryId: 15,
    },
    {
        id: 7,
        name: "Шаурма с говядиной",
        description:
            "Говядина, соус шашлычный, соус чесночный, помидор, морковь, маринованные огурцы, пекинская капуста, лук, зелень",
        slug: "shaurma-s-govyadinoy",
        weightValue: 350,
        weightUnit: "г",
        price: 484,
        categoryId: 15,
    },
    {
        id: 8,
        name: "Шаурма с семгой",
        description:
            "Семга, соус наршараб, соус чесночный, помидор, маринованные огурцы, морковь, лук, пекинская капуста, зелень",
        slug: "shaurma-s-semgoy",
        weightValue: 350,
        weightUnit: "г",
        price: 605,
        categoryId: 15,
    },

    // Бурум
    {
        id: 9,
        name: "Бурум из люля баранины",
        description:
            "Люля-кебаб из баранины, завернутый в армянский лаваш; помидоры, лук, зелень, соус шашлычный",
        slug: "burum-iz-lyulya-baraniny",
        weightValue: 350,
        weightUnit: "г",
        price: 728,
        categoryId: 14,
    },
    {
        id: 10,
        name: "Бурум из люля курицы",
        description:
            "Люля-кебаб куриный, завернутый в армянский лаваш; помидоры, лук, зелень, соус шашлычный",
        slug: "burum-iz-lyulya-kuricy",
        weightValue: 350,
        weightUnit: "г",
        price: 605,
        categoryId: 14,
    },
    {
        id: 11,
        name: "Бурум из люля свинины",
        description:
            "Люля-кебаб из свинины, завернутый в армянский лаваш; помидоры, лук, зелень, соус шашлычный",
        slug: "burum-iz-lyulya-svininy",
        weightValue: 350,
        weightUnit: "г",
        price: 550,
        categoryId: 14,
    },
    {
        id: 12,
        name: "Бурум из люля говядины",
        description:
            "Люля-кебаб из говядины, завернутый в армянский лаваш; помидоры, лук, зелень, соус шашлычный",
        slug: "burum-iz-lyulya-govyadiny",
        weightValue: 350,
        weightUnit: "г",
        price: 660,
        categoryId: 14,
    },
    {
        id: 13,
        name: "Бурум из куриного филе",
        description:
            "Куриное филе, завернутое в армянский лаваш; помидоры, лук, зелень, соус шашлычный",
        slug: "burum-iz-kurinogo-file",
        weightValue: 350,
        weightUnit: "г",
        price: 605,
        categoryId: 14,
    },
    {
        id: 14,
        name: "Бурум из свиной шейки",
        description:
            "Свиная мякоть, завернутая в армянский лаваш; помидоры, лук, зелень, соус шашлычный",
        slug: "burum-iz-svinoy-sheiki",
        weightValue: 350,
        weightUnit: "г",
        price: 728,
        categoryId: 14,
    },
    {
        id: 15,
        name: "Бурум из бараньей мякоти",
        description:
            "Баранья мякоть, завернутая в армянский лаваш; помидоры, лук, зелень, соус шашлычный",
        slug: "burum-iz-baraney-myagkoti",
        weightValue: 350,
        weightUnit: "г",
        price: 1155,
        categoryId: 14,
    },
    {
        id: 16,
        name: "Бурум из розовой телятины",
        description:
            "Шашлык из розовой телятины, завернутый в армянский лаваш; помидоры, лук, зелень, соус шашлычный",
        slug: "burum-iz-rozovoy-telyatiny",
        weightValue: 350,
        weightUnit: "г",
        price: 1045,
        categoryId: 14,
    },

    // На углях -> Шашлык
    {
        id: 17,
        name: "Свиная мякоть",
        description:
            "Свиная мякоть, лук, зелень, шашлычный соус, лаваш армянский",
        slug: "svinaya-myagkot",
        weightValue: 250,
        weightUnit: "г",
        price: 770,
        categoryId: 10,
    },
    {
        id: 18,
        name: "Шашлык из розовой телятины",
        description:
            "Розовая телятина, лук, зелень, шашлычный соус, лаваш армянский",
        slug: "shashlyk-iz-rozovoy-telyatiny",
        weightValue: 250,
        weightUnit: "г",
        price: 990,
        categoryId: 10,
    },
    {
        id: 19,
        name: "Шашлык из бараньей корейки",
        description:
            "Баранья корейка, лук, зелень, шашлычный соус, лаваш армянский",
        slug: "shashlyk-iz-baraney-koreyki",
        weightValue: 250,
        weightUnit: "г",
        price: 1610,
        categoryId: 10,
    },
    {
        id: 20,
        name: "Шашлык из бараньей мякоти",
        description:
            "Баранья мякоть, лук, зелень, шашлычный соус, лаваш армянский",
        slug: "shashlyk-iz-baraney-myagkoti",
        weightValue: 250,
        weightUnit: "г",
        price: 1210,
        categoryId: 10,
    },
    {
        id: 21,
        name: "Шашлык из куриных сердечек",
        description:
            "Подается с картофелем фри. Лук, зелень, шашлычный соус, лаваш армянский",
        slug: "shashlyk-iz-kurinyh-serdechek-s-kartofelem-fri",
        weightValue: 200,
        weightUnit: "г",
        price: 550,
        categoryId: 10,
    },
    {
        id: 22,
        name: "Шашлык из куриных крыльев",
        description:
            "Куриные крылья, лук, зелень, шашлычный соус, лаваш армянский",
        slug: "shashlyk-iz-kurinyh-krylev",
        weightValue: 250,
        weightUnit: "г",
        price: 550,
        categoryId: 10,
    },
    {
        id: 23,
        name: "Шашлык из куриного филе",
        description:
            "Куриная мякоть, лук, зелень, шашлычный соус, лаваш армянский",
        slug: "shashlyk-iz-kurinogo-file",
        weightValue: 250,
        weightUnit: "г",
        price: 605,
        categoryId: 10,
    },
    {
        id: 24,
        name: "Перепела на мангале",
        description: "Перепелки, лук, зелень, шашлычный соус, лаваш армянский",
        slug: "perepela-na-mangale",
        weightValue: 2,
        weightUnit: "шт",
        price: 825,
        categoryId: 10,
    },

    // На углях -> Люля-кебаб
    {
        id: 25,
        name: "Люля-кебаб из свинины",
        description: "Лук, зелень, шашлычный соус, лаваш армянский",
        slug: "lyulya-kebab-iz-svininy",
        weightValue: 250,
        weightUnit: "г",
        price: 605,
        categoryId: 13,
    },
    {
        id: 26,
        name: "Люля-кебаб из говядины",
        description: "Лук, зелень, шашлычный соус, лаваш армянский",
        slug: "lyulya-kebab-iz-govyadiny",
        weightValue: 250,
        weightUnit: "г",
        price: 660,
        categoryId: 13,
    },
    {
        id: 27,
        name: "Люля-кебаб из баранины",
        description: "Лук, зелень, шашлычный соус, лаваш армянский",
        slug: "lyulya-kebab-iz-baraniny",
        weightValue: 250,
        weightUnit: "г",
        price: 715,
        categoryId: 13,
    },
    {
        id: 28,
        name: "Люля-кебаб из курицы",
        description: "Лук, зелень, шашлычный соус, лаваш армянский",
        slug: "lyulya-kebab-iz-kuricy",
        weightValue: 250,
        weightUnit: "г",
        price: 605,
        categoryId: 13,
    },

    // На углях -> Рыба гриль
    {
        id: 29,
        name: "Сибас на мангале",
        description: "Сибас, соус наршараб, лимон, лаваш армянский",
        slug: "sibas-na-mangale",
        weightValue: 300,
        weightUnit: "г",
        price: 1155,
        categoryId: 12,
    },
    {
        id: 30,
        name: "Форель на мангале",
        description: "Форель, соус наршараб, лимон, лаваш армянский",
        slug: "forel-na-mangale",
        weightValue: 300,
        weightUnit: "г",
        price: 968,
        categoryId: 12,
    },
    {
        id: 31,
        name: "Дорадо на мангале",
        description: "Дорадо, соус наршараб, лимон, лаваш армянский",
        slug: "dorado-na-mangale",
        weightValue: 300,
        weightUnit: "г",
        price: 1155,
        categoryId: 12,
    },
    {
        id: 32,
        name: "Семга на мангале",
        description: "Стейк из семги, соус наршараб, лимон, лаваш армянский",
        slug: "semga-na-mangale",
        weightValue: 200,
        weightUnit: "г",
        price: 1485,
        categoryId: 12,
    },
    {
        id: 33,
        name: "Стерлядь на мангале",
        description: "Стейк из стерляди, соус наршараб, лимон, лаваш армянский",
        slug: "sterlyad-na-mangale",
        weightValue: 250,
        weightUnit: "г",
        price: 1650,
        categoryId: 12,
    },

    // На углях -> Овощи гриль
    {
        id: 34,
        name: "Овощной микс на углях",
        description:
            "Цукини, перец болгарский, кукуруза, соус чесночный, зелень, лаваш армянский",
        slug: "ovoshchnoy-miks-na-uglyah",
        weightValue: 200,
        weightUnit: "г",
        price: 583,
        categoryId: 11,
    },
    {
        id: 35,
        name: "Шампиньоны на углях",
        description: "Шампиньоны, соус чесночный, зелень, лаваш армянский",
        slug: "shampinony-na-uglyah",
        weightValue: 200,
        weightUnit: "г",
        price: 559,
        categoryId: 11,
    },
    {
        id: 36,
        name: "Картофель молодой на углях",
        description:
            "Картофель молодой, соус чесночный, зелень, лаваш армянский",
        slug: "kartofel-molodoy-na-uglyah",
        weightValue: 200,
        weightUnit: "г",
        price: 363,
        categoryId: 11,
    },
    {
        id: 37,
        name: "Перец Армянский острый",
        description: "Острый перец на углях",
        slug: "perec-armyanskiy-ostryy",
        weightValue: 1,
        weightUnit: "шт",
        price: 275,
        categoryId: 11,
    },
    {
        id: 38,
        name: "Баклажан на углях",
        description: "Баклажан на углях",
        slug: "baklazhan-na-uglyah",
        weightValue: 1,
        weightUnit: "шт",
        price: 275,
        categoryId: 11,
    },
    {
        id: 39,
        name: "Помидор на углях",
        description: "Помидор на углях",
        slug: "pomidor-na-uglyah",
        weightValue: 1,
        weightUnit: "шт",
        price: 275,
        categoryId: 11,
    },
    {
        id: 40,
        name: "Перец болгарский на углях",
        description: "Болгарский перец на углях",
        slug: "perec-bolgarskiy-na-uglyah",
        weightValue: 1,
        weightUnit: "шт",
        price: 275,
        categoryId: 11,
    },

    // Соусы
    {
        id: 41,
        name: "Сырный",
        description: "Сырный соус",
        slug: "syrnyy-sous",
        weightValue: 50,
        weightUnit: "г",
        price: 77,
        categoryId: 9,
    },
    {
        id: 42,
        name: "Кетчуп",
        description: "Классический кетчуп",
        slug: "ketchup",
        weightValue: 50,
        weightUnit: "г",
        price: 77,
        categoryId: 9,
    },
    {
        id: 43,
        name: "Шашлычный",
        description: "Шашлычный соус",
        slug: "shashlychnyy-sous",
        weightValue: 50,
        weightUnit: "г",
        price: 66,
        categoryId: 9,
    },
    {
        id: 44,
        name: "Чесночный",
        description: "Чесночный соус",
        slug: "chesnochnyy-sous",
        weightValue: 50,
        weightUnit: "г",
        price: 66,
        categoryId: 9,
    },
    {
        id: 45,
        name: "Соус наршараб",
        description: "Гранатовый соус наршараб",
        slug: "sous-narsharab",
        weightValue: 50,
        weightUnit: "г",
        price: 110,
        categoryId: 9,
    },
    {
        id: 46,
        name: "Соус сацебели",
        description: "Соус сацебели",
        slug: "sous-sacebeli",
        weightValue: 50,
        weightUnit: "г",
        price: 88,
        categoryId: 9,
    },
    {
        id: 47,
        name: "Барбекю",
        description: "Соус барбекю",
        slug: "barbekyu",
        weightValue: 50,
        weightUnit: "г",
        price: 77,
        categoryId: 9,
    },
    {
        id: 48,
        name: "Аджика",
        description: "Острая аджика",
        slug: "adzhika",
        weightValue: 50,
        weightUnit: "г",
        price: 77,
        categoryId: 9,
    },

    // Салаты
    {
        id: 49,
        name: "Цезарь с курицей",
        description:
            "Филе куриной грудки, айсберг, помидор черри, сыр пармезан, сухарики, соус цезарь",
        slug: "cezar-s-kuricey",
        weightValue: 250,
        weightUnit: "г",
        price: 605,
        categoryId: 6,
    },
    {
        id: 50,
        name: "Цезарь с тигровыми креветками",
        description:
            "Тигровые креветки, айсберг, помидор черри, сыр пармезан, сухарики, соус цезарь",
        slug: "cezar-s-tigrovymi-krevetkami",
        weightValue: 250,
        weightUnit: "г",
        price: 693,
        categoryId: 6,
    },
    {
        id: 51,
        name: "Цезарь с семгой",
        description:
            "Семга, айсберг, помидор черри, сыр пармезан, сухарики, соус цезарь",
        slug: "cezar-s-semgoy",
        weightValue: 250,
        weightUnit: "г",
        price: 869,
        categoryId: 6,
    },
    {
        id: 52,
        name: "Овощной салат",
        description:
            "Помидор, огурцы, зелень, подсолнечное масло, соль, айсберг, лук, болгарский перец",
        slug: "ovoshchnoy-salat",
        weightValue: 250,
        weightUnit: "г",
        price: 517,
        categoryId: 6,
    },
    {
        id: 53,
        name: "Салат чука",
        description: "Чука, лимон, кунжут, ореховый соус",
        slug: "salat-chuka",
        weightValue: 210,
        weightUnit: "г",
        price: 396,
        categoryId: 6,
    },

    // Супы
    {
        id: 54,
        name: "Борщ из оленины",
        description: "Подаётся с гренками, чесноком и салом, сметана",
        slug: "borshch-iz-oleniny",
        weightValue: 350,
        weightUnit: "г",
        price: 660,
        categoryId: 5,
    },
    {
        id: 55,
        name: "Том ям",
        description:
            "Креветки, лосось, вонголе, рис, кинза, шампиньоны, лайм, лемонграсс",
        slug: "tom-yam",
        weightValue: 450,
        weightUnit: "г",
        price: 880,
        categoryId: 5,
    },

    // Азия -> Wok
    {
        id: 56,
        name: "Удон с креветками",
        description: "Овощной микс, удон, креветки",
        slug: "udon-s-krevetkami",
        weightValue: 350,
        weightUnit: "г",
        price: 660,
        categoryId: 16,
    },
    {
        id: 57,
        name: "Удон с бараниной",
        description: "Овощной микс, удон, баранина",
        slug: "udon-s-baraninoy",
        weightValue: 350,
        weightUnit: "г",
        price: 605,
        categoryId: 16,
    },
    {
        id: 58,
        name: "Удон с говядиной",
        description: "Овощной микс, удон, говядина",
        slug: "udon-s-govyadinoy",
        weightValue: 350,
        weightUnit: "г",
        price: 605,
        categoryId: 16,
    },
    {
        id: 59,
        name: "Удон с курицей",
        description: "Овощной микс, удон, курица",
        slug: "udon-s-kuricey",
        weightValue: 350,
        weightUnit: "г",
        price: 550,
        categoryId: 16,
    },
    {
        id: 60,
        name: "Удон с семгой",
        description: "Овощной микс, удон, семга",
        slug: "udon-s-semgoy",
        weightValue: 350,
        weightUnit: "г",
        price: 660,
        categoryId: 16,
    },
    {
        id: 61,
        name: "Удон со свининой",
        description: "Овощной микс, удон, свинина",
        slug: "udon-so-svininoy",
        weightValue: 350,
        weightUnit: "г",
        price: 583,
        categoryId: 16,
    },

    {
        id: 98,
        name: "Ролл Филадельфия",
        description:
            "Нори, рис, сливочный сыр, свежий огурец, слабосолёный лосось",
        slug: "roll-filadelfiya",
        weightValue: 240,
        weightUnit: "г",
        price: 792,
        categoryId: 17,
    },
    {
        id: 99,
        name: "Ролл Канада",
        description:
            "Нори, рис, сливочный сыр, огурец, лосось, угорь, соус унаги, кунжут",
        slug: "roll-kanada",
        weightValue: 250,
        weightUnit: "г",
        price: 792,
        categoryId: 17,
    },
    {
        id: 100,
        name: "Ролл Калифорния с лососем",
        description: "Рис, нори, лосось, свежий огурец, авокадо, икра масаго",
        slug: "roll-kaliforniya-s-lososem",
        weightValue: 220,
        weightUnit: "г",
        price: 720,
        categoryId: 17,
    },
    {
        id: 101,
        name: "Ролл Калифорния с угрём",
        description:
            "Рис, нори, угорь, сливочный сыр, огурец, икра масаго, соус унаги",
        slug: "roll-kaliforniya-s-ugrem",
        weightValue: 220,
        weightUnit: "г",
        price: 720,
        categoryId: 17,
    },
    {
        id: 102,
        name: "Ролл Калифорния",
        description:
            "Рис, нори, крабовый микс, свежий огурец, авокадо, икра масаго",
        slug: "roll-kaliforniya",
        weightValue: 215,
        weightUnit: "г",
        price: 720,
        categoryId: 17,
    },

    // Закуски
    {
        id: 62,
        name: "Наггетсы",
        description: "Куриные наггетсы",
        slug: "naggetsy",
        weightValue: 9,
        weightUnit: "шт",
        price: 242,
        categoryId: 7,
    },
    {
        id: 63,
        name: "Картофель фри",
        description: "Картофель фри",
        slug: "kartofel-fri",
        weightValue: 180,
        weightUnit: "г",
        price: 275,
        categoryId: 7,
    },
    {
        id: 64,
        name: "Картофель по-деревенски",
        description: "Картофель по-деревенски",
        slug: "kartofel-po-derevenski",
        weightValue: 180,
        weightUnit: "г",
        price: 275,
        categoryId: 7,
    },
    {
        id: 65,
        name: "Сырные палочки",
        description: "Сырные палочки",
        slug: "syrnye-palochki",
        weightValue: 9,
        weightUnit: "шт",
        price: 297,
        categoryId: 7,
    },
    {
        id: 66,
        name: "Луковые кольца",
        description: "Луковые кольца",
        slug: "lukovye-kolca",
        weightValue: 11,
        weightUnit: "шт",
        price: 242,
        categoryId: 7,
    },
    {
        id: 67,
        name: "Кальмаровые кольца",
        description: "Кальмаровые кольца",
        slug: "kalmarovye-kolca",
        weightValue: 180,
        weightUnit: "г",
        price: 220,
        categoryId: 7,
    },
    {
        id: 68,
        name: "Батат",
        description: "Батат фри",
        slug: "batat",
        weightValue: 180,
        weightUnit: "г",
        price: 253,
        categoryId: 7,
    },

    // Завтраки
    {
        id: 69,
        name: "Каша овсяная",
        description:
            "Базовая овсяная каша. Добавки: с лесными ягодами +55 ₽, с вареньем +44 ₽, с мёдом +44 ₽",
        slug: "kasha-ovsyanaya",
        weightValue: 250,
        weightUnit: "г",
        price: 220,
        categoryId: 1,
    },
    {
        id: 70,
        name: "Сырники",
        description:
            "Базовые сырники. Добавки: с вареньем +44 ₽, с мёдом +44 ₽, со сметаной +33 ₽, со сгущёнкой +33 ₽",
        slug: "syrniki",
        weightValue: 200,
        weightUnit: "г",
        price: 275,
        categoryId: 1,
    },
    {
        id: 71,
        name: "Сэндвич с ветчиной",
        description: "Сэндвич с ветчиной",
        slug: "sendvich-s-vetchinoy",
        weightValue: 230,
        weightUnit: "г",
        price: 290,
        categoryId: 1,
    },
    {
        id: 72,
        name: "Сэндвич с курицей",
        description: "Сэндвич с курицей",
        slug: "sendvich-s-kuricey",
        weightValue: 230,
        weightUnit: "г",
        price: 290,
        categoryId: 1,
    },
    {
        id: 73,
        name: "Сэндвич с семгой",
        description: "Сэндвич с семгой",
        slug: "sendvich-s-semgoy",
        weightValue: 230,
        weightUnit: "г",
        price: 370,
        categoryId: 1,
    },
    {
        id: 74,
        name: "Омлет",
        description:
            "Базовый омлет. Добавки: с ветчиной +55 ₽, с беконом +77 ₽, с помидорами +55 ₽, с сыром +55 ₽",
        slug: "omlet",
        weightValue: 250,
        weightUnit: "г",
        price: 275,
        categoryId: 1,
    },
    {
        id: 75,
        name: "Глазунья",
        description:
            "Базовая глазунья. Добавки: с ветчиной +55 ₽, с беконом +77 ₽, с помидорами +55 ₽, с сыром +55 ₽",
        slug: "glazunya",
        weightValue: 170,
        weightUnit: "г",
        price: 200,
        categoryId: 1,
    },
    {
        id: 76,
        name: "Яичница с помидорами",
        description: "Яичница с помидорами",
        slug: "yaichnica-s-pomidorami",
        weightValue: 250,
        weightUnit: "г",
        price: 770,
        categoryId: 1,
    },

    // Напитки -> Горячие напитки
    {
        id: 77,
        name: "Эспрессо",
        description: "Горячий кофейный напиток",
        slug: "espresso",
        weightValue: 40,
        weightUnit: "мл",
        price: 143,
        categoryId: 18,
    },
    {
        id: 78,
        name: "Американо",
        description: "Горячий кофейный напиток",
        slug: "americano",
        weightValue: 300,
        weightUnit: "мл",
        price: 187,
        categoryId: 18,
    },
    {
        id: 79,
        name: "Капучино",
        description: "Горячий кофейный напиток",
        slug: "kapuchino",
        weightValue: 300,
        weightUnit: "мл",
        price: 220,
        categoryId: 18,
    },
    {
        id: 80,
        name: "Латте",
        description: "Горячий кофейный напиток",
        slug: "latte",
        weightValue: 300,
        weightUnit: "мл",
        price: 220,
        categoryId: 18,
    },
    {
        id: 81,
        name: "Кофе на песке",
        description: "Кофе, приготовленный на песке",
        slug: "kofe-na-peske",
        weightValue: 100,
        weightUnit: "мл",
        price: 275,
        categoryId: 18,
    },
    {
        id: 82,
        name: "Кофе на песке на молоке",
        description: "Кофе на песке с молоком",
        slug: "kofe-na-peske-na-moloke",
        weightValue: 100,
        weightUnit: "мл",
        price: 330,
        categoryId: 18,
    },
    {
        id: 83,
        name: "Горячий шоколад",
        description: "Горячий шоколад",
        slug: "goryachiy-shokolad",
        weightValue: 300,
        weightUnit: "мл",
        price: 220,
        categoryId: 18,
    },
    {
        id: 84,
        name: "Чай в пакетиках",
        description: "Пакетированный чай",
        slug: "chay-v-paketikah",
        weightValue: 200,
        weightUnit: "мл",
        price: 88,
        categoryId: 18,
    },
    {
        id: 85,
        name: "Чай в ассортименте",
        description: "Чёрный с чабрецом, зелёный, улун, фруктовый",
        slug: "chay-v-assortimente",
        weightValue: 500,
        weightUnit: "мл",
        price: 385,
        categoryId: 18,
    },

    // Напитки -> Холодные напитки
    {
        id: 86,
        name: "Coca-Cola",
        description: "Газированный напиток",
        slug: "coca-cola",
        weightValue: 330,
        weightUnit: "мл",
        price: 275,
        categoryId: 19,
    },
    {
        id: 87,
        name: "Fanta",
        description: "Газированный напиток",
        slug: "fanta",
        weightValue: 330,
        weightUnit: "мл",
        price: 275,
        categoryId: 19,
    },
    {
        id: 88,
        name: "Evervess cola",
        description: "Газированный напиток",
        slug: "evervess-cola",
        weightValue: 330,
        weightUnit: "мл",
        price: 110,
        categoryId: 19,
    },
    {
        id: 89,
        name: "Сок Rich",
        description: "Сок Rich",
        slug: "sok-rich",
        weightValue: 200,
        weightUnit: "мл",
        price: 176,
        categoryId: 19,
    },
    {
        id: 90,
        name: "Сок Bundaberg в ассортименте",
        description: "Напиток Bundaberg в ассортименте",
        slug: "sok-bundaberg",
        weightValue: 375,
        weightUnit: "мл",
        price: 462,
        categoryId: 19,
    },
    {
        id: 91,
        name: "Сок Lebl",
        description: "Маракуйя, персик, виноград, апельсин, киви",
        slug: "sok-lebl",
        weightValue: 500,
        weightUnit: "мл",
        price: 462,
        categoryId: 19,
    },
    {
        id: 92,
        name: "Rich Tea",
        description: "Холодный чай",
        slug: "rich-tea",
        weightValue: 500,
        weightUnit: "мл",
        price: 176,
        categoryId: 19,
    },
    {
        id: 93,
        name: "Aqua Minerale",
        description: "Минеральная вода",
        slug: "aqua-minerale",
        weightValue: 500,
        weightUnit: "мл",
        price: 100,
        categoryId: 19,
    },
    {
        id: 94,
        name: "Вода Baikal",
        description: "Вода Baikal",
        slug: "voda-baikal",
        weightValue: 500,
        weightUnit: "мл",
        price: 308,
        categoryId: 19,
    },
    {
        id: 95,
        name: "Компот Ararat",
        description: "Компот",
        slug: "kompot-ararat",
        weightValue: 1,
        weightUnit: "л",
        price: 572,
        categoryId: 19,
    },
    {
        id: 96,
        name: "Морс 300 мл",
        description: "Морс",
        slug: "mors-300",
        weightValue: 300,
        weightUnit: "мл",
        price: 110,
        categoryId: 19,
    },
    {
        id: 97,
        name: "Морс 500 мл",
        description: "Морс",
        slug: "mors-500",
        weightValue: 500,
        weightUnit: "мл",
        price: 165,
        categoryId: 19,
    },
];
